# Generated by Django 4.2.5 on 2023-09-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='full_name',
            new_name='name',
        ),
    ]
